# Server Port Configuration
server.port=8082

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/motorcycle_parts
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Jackson properties formatting
spring.jackson.serialization.indent_output=true
